language: python
python:
  - '3.7'
cache: pip

branches:
  only:
    - /.*/

install:
  - pip install -U pip
  - pip --version
  - pip install -r requirements.txt
  - npm install -g markdownlint-cli
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - molecule --version

script:
  - markdownlint .
  - molecule lint
