---
- name: Subscribe {{ ansible_fqdn }}
  redhat_subscription:
    activationkey: "{{ rhsm_activationkey }}"
    auto_attach: "{{ rhsm_auto_attach }}"
    consumer_id: "{{ rhsm_consumer_id }}"
    consumer_name: "{{ rhsm_consumer_name }}"
    consumer_type: "{{ rhsm_consumer_type }}"
    environment: "{{ rhsm_environment }}"
    force_register: "{{ rhsm_force_register }}"
    org_id: "{{ rhsm_org_id }}"
    password: "{{ rhsm_password }}"
    pool: "{{ rhsm_pool }}"
    pool_ids: "{{ rhsm_pool_ids }}"
    release: "{{ rhsm_release }}"
    rhsm_baseurl: "{{ rhsm_rhsm_baseurl }}"
    rhsm_repo_ca_cert: "{{ rhsm_rhsm_repo_ca_cert }}"
    server_hostname: "{{ rhsm_server_hostname }}"
    server_insecure: "{{ rhsm_server_insecure }}"
    server_proxy_hostname: "{{ rhsm_server_proxy_hostname }}"
    server_proxy_password: "{{ rhsm_server_proxy_password }}"
    server_proxy_port: "{{ rhsm_server_proxy_port }}"
    server_proxy_user: "{{ rhsm_server_proxy_user }}"
    state: "{{ rhsm_state }}"
    username: "{{ rhsm_username }}"

    #- name: Enable RHSM repositories
    # rhsm_repository:
    # name: "{{ rhsm_repos }}"
    # purge: "{{ rhsm_purge }}"
    # state: "{{ rhsm_repo_state }}"
