---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    box: generic/rhel8
    memory: 1024
    cpus: 1
    groups:
      - rhel
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
